/* Automatically @generated by tree-sitter */

#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 1
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_DOLLAR = 8,
  sym_verbatim_block = 9,
  anon_sym_POUNDinclude = 10,
  anon_sym_POUNDincludeEtc = 11,
  anon_sym_POUNDincludeIfPresent = 12,
  anon_sym_POUNDsinclude = 13,
  anon_sym_POUNDcalc = 14,
  anon_sym_POUNDcodeStream = 15,
  aux_sym__c_code_block_token1 = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_on = 19,
  anon_sym_off = 20,
  anon_sym_yes = 21,
  anon_sym_no = 22,
  sym_identifier = 23,
  sym_number = 24,
  sym_string = 25,
  sym_line_comment = 26,
  sym_block_comment = 27,
  sym_source_file = 28,
  sym__element = 29,
  sym_entry = 30,
  sym_dict = 31,
  sym__value = 32,
  sym_dimensions = 33,
  sym_list = 34,
  sym_variable = 35,
  sym_include_directive = 36,
  sym_calc_directive = 37,
  sym_code_stream = 38,
  aux_sym__c_code_block = 39,
  sym_boolean = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_entry_repeat1 = 42,
  aux_sym_dimensions_repeat1 = 43,
  aux_sym_list_repeat1 = 44,
  alias_sym_code_block = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOLLAR] = "$",
  [sym_verbatim_block] = "verbatim_block",
  [anon_sym_POUNDinclude] = "#include",
  [anon_sym_POUNDincludeEtc] = "#includeEtc",
  [anon_sym_POUNDincludeIfPresent] = "#includeIfPresent",
  [anon_sym_POUNDsinclude] = "#sinclude",
  [anon_sym_POUNDcalc] = "#calc",
  [anon_sym_POUNDcodeStream] = "#codeStream",
  [aux_sym__c_code_block_token1] = "_c_code_block_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_on] = "on",
  [anon_sym_off] = "off",
  [anon_sym_yes] = "yes",
  [anon_sym_no] = "no",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__element] = "_element",
  [sym_entry] = "entry",
  [sym_dict] = "dict",
  [sym__value] = "_value",
  [sym_dimensions] = "dimensions",
  [sym_list] = "list",
  [sym_variable] = "variable",
  [sym_include_directive] = "include_directive",
  [sym_calc_directive] = "calc_directive",
  [sym_code_stream] = "code_stream",
  [aux_sym__c_code_block] = "_c_code_block",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_entry_repeat1] = "entry_repeat1",
  [aux_sym_dimensions_repeat1] = "dimensions_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [alias_sym_code_block] = "code_block",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_verbatim_block] = sym_verbatim_block,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [anon_sym_POUNDincludeEtc] = anon_sym_POUNDincludeEtc,
  [anon_sym_POUNDincludeIfPresent] = anon_sym_POUNDincludeIfPresent,
  [anon_sym_POUNDsinclude] = anon_sym_POUNDsinclude,
  [anon_sym_POUNDcalc] = anon_sym_POUNDcalc,
  [anon_sym_POUNDcodeStream] = anon_sym_POUNDcodeStream,
  [aux_sym__c_code_block_token1] = aux_sym__c_code_block_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_off] = anon_sym_off,
  [anon_sym_yes] = anon_sym_yes,
  [anon_sym_no] = anon_sym_no,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__element] = sym__element,
  [sym_entry] = sym_entry,
  [sym_dict] = sym_dict,
  [sym__value] = sym__value,
  [sym_dimensions] = sym_dimensions,
  [sym_list] = sym_list,
  [sym_variable] = sym_variable,
  [sym_include_directive] = sym_include_directive,
  [sym_calc_directive] = sym_calc_directive,
  [sym_code_stream] = sym_code_stream,
  [aux_sym__c_code_block] = aux_sym__c_code_block,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_entry_repeat1] = aux_sym_entry_repeat1,
  [aux_sym_dimensions_repeat1] = aux_sym_dimensions_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [alias_sym_code_block] = alias_sym_code_block,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_verbatim_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDincludeEtc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDincludeIfPresent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDsinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDcalc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDcodeStream] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__c_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_off] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_no] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_dimensions] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_calc_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_code_stream] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__c_code_block] = {
    .visible = false,
    .named = false,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dimensions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_code_block] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
  [1] =
    {field_value, 0},
  [2] =
    {field_key, 0},
    {field_value, 1, .inherited = true},
  [4] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [5] = {
    [2] = alias_sym_code_block,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__c_code_block, 2,
    aux_sym__c_code_block,
    alias_sym_code_block,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 19,
  [23] = 20,
  [24] = 24,
  [25] = 15,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 16,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '"', 1,
        '#', 12,
        '$', 59,
        '(', 57,
        ')', 58,
        '.', 47,
        '/', 3,
        ';', 52,
        '[', 55,
        ']', 56,
        'f', 79,
        'n', 86,
        'o', 83,
        't', 87,
        'y', 80,
        '{', 53,
        '}', 54,
        '+', 6,
        '-', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(45);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(96);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(97);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(68);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == 'P') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'S') ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == '{') ADVANCE(2);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(8);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(66);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 45:
      if (lookahead == '}') ADVANCE(60);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 46:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 49:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 50:
      if (eof) ADVANCE(51);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_verbatim_block);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      if (lookahead == 'E') ADVANCE(42);
      if (lookahead == 'I') ADVANCE(27);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_POUNDincludeEtc);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_POUNDincludeIfPresent);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_POUNDsinclude);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUNDcalc);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUNDcodeStream);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead == '\n') ADVANCE(72);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(96);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead == '*') ADVANCE(70);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead == '*') ADVANCE(69);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead == '*') ADVANCE(69);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead == '/') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__c_code_block_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_on);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_off);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_yes);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_no);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(84);
      if (lookahead == 'n') ADVANCE(75);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(89);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(78);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(82);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(81);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(93);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 50},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 50},
  [19] = {.lex_state = 50},
  [20] = {.lex_state = 50},
  [21] = {.lex_state = 50},
  [22] = {.lex_state = 50},
  [23] = {.lex_state = 50},
  [24] = {.lex_state = 50},
  [25] = {.lex_state = 50},
  [26] = {.lex_state = 50},
  [27] = {.lex_state = 50},
  [28] = {.lex_state = 50},
  [29] = {.lex_state = 50},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 50},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 50},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 50},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_verbatim_block] = ACTIONS(1),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [anon_sym_POUNDincludeEtc] = ACTIONS(1),
    [anon_sym_POUNDincludeIfPresent] = ACTIONS(1),
    [anon_sym_POUNDsinclude] = ACTIONS(1),
    [anon_sym_POUNDcalc] = ACTIONS(1),
    [anon_sym_POUNDcodeStream] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_off] = ACTIONS(1),
    [anon_sym_yes] = ACTIONS(1),
    [anon_sym_no] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__element] = STATE(21),
    [sym_entry] = STATE(21),
    [sym_include_directive] = STATE(21),
    [sym_code_stream] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_POUNDinclude] = ACTIONS(7),
    [anon_sym_POUNDincludeEtc] = ACTIONS(9),
    [anon_sym_POUNDincludeIfPresent] = ACTIONS(9),
    [anon_sym_POUNDsinclude] = ACTIONS(9),
    [anon_sym_POUNDcodeStream] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_dict] = STATE(24),
    [sym__value] = STATE(17),
    [sym_dimensions] = STATE(17),
    [sym_list] = STATE(17),
    [sym_variable] = STATE(17),
    [sym_calc_directive] = STATE(17),
    [sym_boolean] = STATE(17),
    [aux_sym_entry_repeat1] = STATE(6),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_verbatim_block] = ACTIONS(25),
    [anon_sym_POUNDcalc] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [anon_sym_on] = ACTIONS(29),
    [anon_sym_off] = ACTIONS(29),
    [anon_sym_yes] = ACTIONS(29),
    [anon_sym_no] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_number] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_dict] = STATE(4),
    [sym__value] = STATE(4),
    [sym_dimensions] = STATE(4),
    [sym_list] = STATE(4),
    [sym_variable] = STATE(4),
    [sym_calc_directive] = STATE(4),
    [sym_boolean] = STATE(4),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_verbatim_block] = ACTIONS(37),
    [anon_sym_POUNDcalc] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [anon_sym_on] = ACTIONS(29),
    [anon_sym_off] = ACTIONS(29),
    [anon_sym_yes] = ACTIONS(29),
    [anon_sym_no] = ACTIONS(29),
    [sym_identifier] = ACTIONS(39),
    [sym_number] = ACTIONS(37),
    [sym_string] = ACTIONS(37),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_dict] = STATE(5),
    [sym__value] = STATE(5),
    [sym_dimensions] = STATE(5),
    [sym_list] = STATE(5),
    [sym_variable] = STATE(5),
    [sym_calc_directive] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_list_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_verbatim_block] = ACTIONS(43),
    [anon_sym_POUNDcalc] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [anon_sym_on] = ACTIONS(29),
    [anon_sym_off] = ACTIONS(29),
    [anon_sym_yes] = ACTIONS(29),
    [anon_sym_no] = ACTIONS(29),
    [sym_identifier] = ACTIONS(45),
    [sym_number] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_dict] = STATE(5),
    [sym__value] = STATE(5),
    [sym_dimensions] = STATE(5),
    [sym_list] = STATE(5),
    [sym_variable] = STATE(5),
    [sym_calc_directive] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_list_repeat1] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(56),
    [anon_sym_DOLLAR] = ACTIONS(58),
    [sym_verbatim_block] = ACTIONS(61),
    [anon_sym_POUNDcalc] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [anon_sym_on] = ACTIONS(67),
    [anon_sym_off] = ACTIONS(67),
    [anon_sym_yes] = ACTIONS(67),
    [anon_sym_no] = ACTIONS(67),
    [sym_identifier] = ACTIONS(70),
    [sym_number] = ACTIONS(61),
    [sym_string] = ACTIONS(61),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(17),
    [sym_dimensions] = STATE(17),
    [sym_list] = STATE(17),
    [sym_variable] = STATE(17),
    [sym_calc_directive] = STATE(17),
    [sym_boolean] = STATE(17),
    [aux_sym_entry_repeat1] = STATE(7),
    [anon_sym_SEMI] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [sym_verbatim_block] = ACTIONS(25),
    [anon_sym_POUNDcalc] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [anon_sym_on] = ACTIONS(29),
    [anon_sym_off] = ACTIONS(29),
    [anon_sym_yes] = ACTIONS(29),
    [anon_sym_no] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_number] = ACTIONS(25),
    [sym_string] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__value] = STATE(17),
    [sym_dimensions] = STATE(17),
    [sym_list] = STATE(17),
    [sym_variable] = STATE(17),
    [sym_calc_directive] = STATE(17),
    [sym_boolean] = STATE(17),
    [aux_sym_entry_repeat1] = STATE(7),
    [anon_sym_SEMI] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(80),
    [anon_sym_DOLLAR] = ACTIONS(83),
    [sym_verbatim_block] = ACTIONS(86),
    [anon_sym_POUNDcalc] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(92),
    [anon_sym_false] = ACTIONS(92),
    [anon_sym_on] = ACTIONS(92),
    [anon_sym_off] = ACTIONS(92),
    [anon_sym_yes] = ACTIONS(92),
    [anon_sym_no] = ACTIONS(92),
    [sym_identifier] = ACTIONS(95),
    [sym_number] = ACTIONS(86),
    [sym_string] = ACTIONS(86),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(98), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [26] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(102), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [52] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(106), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [78] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(112), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(110), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [104] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(116), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(114), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [130] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(120), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(118), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [156] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(124), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(122), 10,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [182] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(128), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(126), 9,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [207] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(132), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(130), 9,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [232] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(136), 7,
      anon_sym_true,
      anon_sym_false,
      anon_sym_on,
      anon_sym_off,
      anon_sym_yes,
      anon_sym_no,
      sym_identifier,
    ACTIONS(134), 8,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_DOLLAR,
      sym_verbatim_block,
      anon_sym_POUNDcalc,
      sym_number,
      sym_string,
  [256] = 7,
    ACTIONS(140), 1,
      anon_sym_POUNDinclude,
    ACTIONS(146), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(149), 2,
      sym_identifier,
      sym_string,
    ACTIONS(143), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(18), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [287] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(11), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(13), 2,
      sym_identifier,
      sym_string,
    ACTIONS(9), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(20), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [317] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(11), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(13), 2,
      sym_identifier,
      sym_string,
    ACTIONS(9), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(18), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [347] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(11), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(13), 2,
      sym_identifier,
      sym_string,
    ACTIONS(9), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(18), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [377] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(11), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(13), 2,
      sym_identifier,
      sym_string,
    ACTIONS(9), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(23), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [407] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDinclude,
    ACTIONS(11), 1,
      anon_sym_POUNDcodeStream,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(13), 2,
      sym_identifier,
      sym_string,
    ACTIONS(9), 3,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
    STATE(18), 5,
      sym__element,
      sym_entry,
      sym_include_directive,
      sym_code_stream,
      aux_sym_source_file_repeat1,
  [437] = 3,
    ACTIONS(164), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(162), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [455] = 3,
    ACTIONS(128), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [473] = 3,
    ACTIONS(168), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(166), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [491] = 3,
    ACTIONS(172), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(170), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [509] = 3,
    ACTIONS(176), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(174), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [527] = 3,
    ACTIONS(132), 1,
      anon_sym_POUNDinclude,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_POUNDincludeEtc,
      anon_sym_POUNDincludeIfPresent,
      anon_sym_POUNDsinclude,
      anon_sym_POUNDcodeStream,
      sym_identifier,
      sym_string,
  [545] = 5,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
    ACTIONS(182), 1,
      aux_sym__c_code_block_token1,
    STATE(32), 1,
      aux_sym__c_code_block,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
  [562] = 5,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 1,
      aux_sym__c_code_block_token1,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym__c_code_block,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
  [579] = 5,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 1,
      aux_sym__c_code_block_token1,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym__c_code_block,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
  [596] = 5,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      aux_sym__c_code_block_token1,
    STATE(33), 1,
      aux_sym__c_code_block,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
  [613] = 2,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(198), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__c_code_block_token1,
  [623] = 4,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    ACTIONS(202), 1,
      sym_number,
    STATE(37), 1,
      aux_sym_dimensions_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [637] = 2,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(193), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__c_code_block_token1,
  [647] = 4,
    ACTIONS(204), 1,
      anon_sym_RBRACK,
    ACTIONS(206), 1,
      sym_number,
    STATE(37), 1,
      aux_sym_dimensions_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [661] = 2,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__c_code_block_token1,
  [671] = 4,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 1,
      aux_sym__c_code_block_token1,
    STATE(31), 1,
      aux_sym__c_code_block,
    ACTIONS(184), 2,
      sym_line_comment,
      sym_block_comment,
  [685] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(211), 2,
      sym_verbatim_block,
      sym_string,
  [694] = 3,
    ACTIONS(213), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [705] = 3,
    ACTIONS(217), 1,
      sym_number,
    STATE(35), 1,
      aux_sym_dimensions_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [716] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(219), 2,
      sym_identifier,
      sym_string,
  [725] = 2,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [733] = 2,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [741] = 2,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [749] = 2,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 26,
  [SMALL_STATE(10)] = 52,
  [SMALL_STATE(11)] = 78,
  [SMALL_STATE(12)] = 104,
  [SMALL_STATE(13)] = 130,
  [SMALL_STATE(14)] = 156,
  [SMALL_STATE(15)] = 182,
  [SMALL_STATE(16)] = 207,
  [SMALL_STATE(17)] = 232,
  [SMALL_STATE(18)] = 256,
  [SMALL_STATE(19)] = 287,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 347,
  [SMALL_STATE(22)] = 377,
  [SMALL_STATE(23)] = 407,
  [SMALL_STATE(24)] = 437,
  [SMALL_STATE(25)] = 455,
  [SMALL_STATE(26)] = 473,
  [SMALL_STATE(27)] = 491,
  [SMALL_STATE(28)] = 509,
  [SMALL_STATE(29)] = 527,
  [SMALL_STATE(30)] = 545,
  [SMALL_STATE(31)] = 562,
  [SMALL_STATE(32)] = 579,
  [SMALL_STATE(33)] = 596,
  [SMALL_STATE(34)] = 613,
  [SMALL_STATE(35)] = 623,
  [SMALL_STATE(36)] = 637,
  [SMALL_STATE(37)] = 647,
  [SMALL_STATE(38)] = 661,
  [SMALL_STATE(39)] = 671,
  [SMALL_STATE(40)] = 685,
  [SMALL_STATE(41)] = 694,
  [SMALL_STATE(42)] = 705,
  [SMALL_STATE(43)] = 716,
  [SMALL_STATE(44)] = 725,
  [SMALL_STATE(45)] = 733,
  [SMALL_STATE(46)] = 741,
  [SMALL_STATE(47)] = 749,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(42),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(3),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(41),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(17),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(40),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(8),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 4), SHIFT_REPEAT(17),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_calc_directive, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_calc_directive, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dimensions, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dimensions, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 1, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 1, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 2, 0, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_directive, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_stream, 4, 0, 5),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_stream, 4, 0, 5),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 3),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry, 3, 0, 3),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__c_code_block, 2, 0, 0), SHIFT_REPEAT(30),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__c_code_block, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__c_code_block, 2, 0, 0), SHIFT_REPEAT(38),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__c_code_block, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dimensions_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dimensions_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__c_code_block, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [223] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_openfoam(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "openfoam",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
